### ISSUE TITLE
Graph looks weird

### ISSUE THREAD

**Issue by cyberjunky** [stash86/ft-dashboard#4] opened 2023-09-10 18:19 UTC
I have it all running, amazing work!
But my graphs looks weird, any idea where to look? Still trying to get around the structure/code...
These are 1h and 4h timeframe strategies.
![image](https://github.com/stash86/ft-dashboard/assets/5447161/bed2abd8-3995-4bc8-913b-b216c1683d2f)

**Comment by stash86** [comment] 2023-09-11 03:36
That's interesting chart.... Let me see if I can create something for debugging it

**Comment by stash86** [comment] 2023-09-11 06:44
Is it possible for me to access that dashboard?

**Comment by stash86** [comment] 2023-09-11 07:58
and by access, I just need to be able to access the page via browser, not gaining any direct access to your server

**Comment by cyberjunky** [comment] 2023-09-11 10:29
I will arrange it, it kind of stops working over time (no graphs or bots now), need to check the docker logs...

**Comment by cyberjunky** [comment] 2023-09-11 10:41
```<br />
<b>Warning</b>:  Undefined array key 4 in <b>/app/app/scripts/fetch_data.php</b> on line <b>98</b><br />
<br />
<b>Warning</b>:  Trying to access array offset on value of type null in <b>/app/app/scripts/fetch_data.php</b> on line <b>98</b><br />
Inserted 2 document(s)
```

**Comment by stash86** [comment] 2023-09-11 10:48
That line try to access the ip at your .json. Did you remove the file?

**Comment by cyberjunky** [comment] 2023-09-11 12:55
The bots.json file was still there, did a complete reinstall and copied .env and bots.jon over and still have this error (full):
The x.x.x.x:pppp part is the first ip_address and port entry in my bots.json, so it finds it, did the format change (different then bots.json.example?)
```
X-Powered-By: PHP/8.2.10
Content-type: text/html; charset=UTF-8

fetch datas from x.x.x.x:pppp
<br />
<b>Warning</b>:  Undefined array key 4 in <b>/app/app/scripts/fetch_data.php</b> on line <b>98</b><br />
<br />
<b>Warning</b>:  Trying to access array offset on value of type null in <b>/app/app/scripts/fetch_data.php</b> on line <b>98</b><br />
Inserted 2 document(s)
```
Have to find some time to debug, it worked before, weird

**Comment by cyberjunky** [comment] 2023-09-11 15:26
I got it working again, went back to last commit of 8 sept like so:
```
$ git log --oneline
0a4d35e (HEAD -> main, origin/main, origin/HEAD) Formatting readme
9e65c5f add live website link and remove unnecessary steps
48fdc97 Revert "add let's encrypt to make the connection into https"
06f6c32 Revert "more changes"
74d7577 more changes
7e44511 add let's encrypt to make the connection into https
99e4ca6 add null check
cb17100 add null check
8ca2d2a add composer.lock to gitignore
327c778 add missing min and max profit
6bb1de3 fix formatting
...

$ git checkout 6bb1de3 .
Updated 5 paths from 53b2aed

$ docker-compose build
$ docker-compose run --rm php composer install
$ docker-compose up -d

You can access my instance here: http://86.86.0.48:12512/  (i will open it temp, only dry run bots)

**Comment by cyberjunky** [comment] 2023-09-13 09:58
Can you have a quick look to my website some time to see what the cause of the weird graph can be?
Something I can check? Still investigating how it all works together

**Comment by stash86** [comment] 2023-09-13 10:14
My concern is why your closed trades are sorted by ID. By default, it should be sorted by close date

**Comment by cyberjunky** [comment] 2023-09-13 10:29
Is that the issue, i run a locally install freqtrade (no docker), stable branch, nothing special I think. Just did another 'setup.sh -u' and restarted. 
The trades are displayed correct in Frequi. Will have a look into the response of the api

**Comment by cyberjunky** [comment] 2023-09-13 11:27
Oke a dirty hack made that work, need to look for real cause, no idea why param doesn't pass through yet...
![Screenshot from 2023-09-13 12-51-28](https://github.com/stash86/ft-dashboard/assets/5447161/d154c7cc-3690-4800-8f47-d1e8957b4aab)

**Comment by stash86** [comment] 2023-09-13 11:41
Closing this as this is caused by #5

**Closed as completed by stash86** 2023-09-13 11:41 UTC
